---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
    commit-message:
      prefix: "ci(actions): "
    labels:
      - ci
    rebase-strategy: auto

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 4
    commit-message:
      prefix: "build(deps): "
    labels:
      - dependencies
    rebase-strategy: auto
