---
- name: configure | Include LDAP in AUTHENTICATION_BACKENDS
  ansible.builtin.set_fact:
    nautobot_authentication_backends: |
      {{ ['django_auth_ldap.backend.LDAPBackend'] + nautobot_authentication_backends }}
  when: nautobot_auth_ldap is defined

- name: configure | Include RemoteUserBackend in AUTHENTICATION_BACKENDS
  ansible.builtin.set_fact:
    nautobot_authentication_backends: |
      {{ ['nautobot.core.authentication.RemoteUserBackend'] + nautobot_authentication_backends }}
  when: nautobot_remote_auth is defined

- name: configure | Configure nautobot_config.py
  ansible.builtin.template:
    src: nautobot_config.py.j2
    dest: "{{ nautobot_root }}/nautobot_config.py"
    owner: "{{ nautobot_system_user }}"
    mode: '0664'
  become: true
  become_user: "{{ nautobot_system_user }}"
  notify: restart_nautobot

- name: configure | Configure uswgi.ini
  ansible.builtin.template:
    src: uwsgi.ini.j2
    dest: "{{ nautobot_root }}/uwsgi.ini"
    owner: "{{ nautobot_system_user }}"
    mode: '0664'
  become: true
  become_user: "{{ nautobot_system_user }}"
  notify: restart_nautobot
