---
- name: install.redhat | install required system packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3
    - python3-devel
    - python3-pip
    - python3-dnf

- name: install.redhat | install system packages for LDAP authentication
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - openldap-devel
  when: nautobot_auth_ldap is defined
