---
- name: install.redhat | Install required system packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3
    - python3-devel
    - python3-pip
    - python3-dnf

- name: install.redhat | Install system packages for LDAP authentication
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - openldap-devel
  when: nautobot_auth_ldap is defined
