---
- name: install.debian | update apt repository cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install.debian | install required system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3
    - python3-pip
    - python3-venv
    - python3-dev

- name: install.debian | install system packages for LDAP authentication
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - libldap2-dev
    - libsasl2-dev
    - libssl-dev
  when: nautobot_auth_ldap is defined
