---
- name: Include system package requirements
  ansible.builtin.include_tasks: "install.{{ ansible_os_family | lower }}.yml"
  args:
    apply:
      become: true

- name: Include Nautobot installation tasks
  ansible.builtin.include_tasks: install.yml
