---
- name: Converge
  hosts: all

  vars:
    nautobot_db_username: nautobot
    nautobot_db_password: nautobot
    nautobot_napalm:
      username: napalm
      password: testing
      timeout: 30
      args: {}
    nautobot_secret_key: "lnvRn_5Bypl8hBV4mMwgsMuHxr6uZvGwJyDqB7fcKqo"
    nautobot_superusers:
      - username: admin
        password: admin
        email: changeme@example.com
    nautobot_plugins:
      - name: nautobot_plugin_nornir
        pip: nautobot-plugin-nornir
        config:
          nornir_settings:
            credentials: "nautobot_plugin_nornir.plugins.credentials.env_vars.CredentialsEnvVars"
            runner:
              plugin: "threaded"
              options:
                num_workers: 20

  roles:
    - role: jvoss.nautobot
