---
name: Release
on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'jvoss.nautobot'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: 'jvoss.nautobot'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Trigger import on Ansible Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
